version: '3'

services:
  phoenix:
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    #environment:
      #POSTGRES_HOST: "localhost" 
      #POSTGRES_PORT: 5432 
      #POSTGRES_DB: "draw_hunts_dev" 
      #POSTGRES_USER: "postgres" 
      #POSTGRES_PASSWORD: "postgres" 
    ports:
      - 4000:4000 # App
      - 4002:4002 # Test
    volumes:
      - .:/app
      - /app/deps
      - /app/assets/node_modules
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres" 
      POSTGRES_PASSWORD: "postgres" 
      PG_DATA: /var/lib/postgresql/data/pgdata
      #POSTGRES_DB: "draw_hunts_dev"
      PGDATA: /tmp
      POOL: 100
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
volumes: 
  pgdata: